########################################################################
 # Copyright (c) Intel Corporation 2023
 # SPDX-License-Identifier: BSD-3-Clause
########################################################################

version: '3.7'
networks:
  edgex-network:
    driver: bridge
services:
  pipeline-val:
    command: /as-pipeline-val -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res -s
    depends_on:
      - security-bootstrapper
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      EDGEX_SECURITY_SECRET_STORE: "true"
      SECRETSTORE_HOST: edgex-vault
      SERVICE_HOST: pipeline-val
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_PROXYSETUP_READYPORT: "54325"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_AUTHMODE: usernamepassword
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_SECRETNAME: redisdb
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-redis
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-redis
      APPLICATIONSETTINGS_SIMHOST: pipeline-val
      APPLICATIONSETTINGS_PIPELINEHOST: pipeline-sim
      APPLICATIONSETTINGS_PIPELINEPORT: 59789
      APPLICATIONSETTINGS_PIPELINEENDPOINT: /api/v1/pipelines
      WRITABLE_LOGLEVEL: DEBUG
    image: aicsd/as-pipeline-val:0.0.0-dev
    networks:
      edgex-network: {}
    ports:
      - 59788:59788/tcp
    read_only: true
    #restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - ${HOME}/data/gateway-files:/tmp/files
      - edgex-init:/edgex-init:z
      - /tmp/edgex/secrets/app-pipeline-val:/tmp/edgex/secrets/app-pipeline-val:ro,z
