[Writable]
LogLevel = "INFO"

[Service]
HealthCheckInterval = "10s"
Host = "localhost"
Port = 59789
ServerBindAddr = "" # Leave blank so default to Host value unless different value is needed.
StartupMsg = "Started the pipeline simulator microservice"
MaxResultCount = 0 # Not currently used by App Services.
MaxRequestSize = 0 # Not currently used by App Services.
RequestTimeout = "15s"

  [Service.CORSConfiguration]
  EnableCORS = true
  CORSAllowCredentials = false
  CORSAllowedOrigin = "*"
  CORSAllowedMethods = "GET, POST, PUT, PATCH, DELETE"
  CORSAllowedHeaders = "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID, DNT, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control"
  CORSExposeHeaders = "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
  CORSMaxAge = 3600

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

[SecretStore]
Type = "vault"
Protocol = "http"
Host = "localhost"
Port = 8200
Path = "app-pipeline-sim/"
TokenFile = "/tmp/edgex/secrets/app-pipeline-sim/secrets-token.json"
RootCaCertPath = ""
ServerName = ""
[SecretStore.Authentication]
  AuthType = "X-Vault-Token"

[Trigger]
Type="edgex-messagebus"
  [Trigger.EdgexMessageBus]
  Type = "redis"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"
    SubscribeTopics="only-file, only-results, file-and-results, multi-file, geti/#"
    [Trigger.EdgexMessageBus.Optional]
    ClientId ="app-pipeline-sim"
    Qos            = "0" # Quality of Service values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive      = "10" # Seconds (must be 2 or greater)
    Retained       = "true"
    AutoReconnect  = "true"
    ConnectTimeout = "15" # Seconds
    SkipCertVerify = "false"
    authmode = "usernamepassword"  # change to "usernamepassword", "clientcert", or "cacert" for secure MQTT messagebus.
    secretname = "redisdb"
    # Default NATS Specific options that need to be here to enable environment variable overrides of them
    Format = "nats"
    RetryOnFailedConnect = "true"
    QueueGroup = ""
    Durable = ""
    AutoProvision = "true"
    Deliver = "new"
    DefaultPubRetryAttempts = "2"
    Subject = "edgex/#" # Required for NATS JetStream only for stream autoprovisioning

[ApplicationSettings]
EvamHost="evam"
EvamPort="8080"
