name: Unit and Integration Tests
run-name: Unit/Integration Test
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read

jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Go ENV
        uses: actions/setup-go@v4
        with: 
          go-version: '1.22.5'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt install libzmq3-dev
      
      - name: Run Unit Tests
        run: make test

  Fuzz_Test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Go ENV
        uses: actions/setup-go@v4
        with: 
          go-version: '1.22.5'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt install libzmq3-dev
      
      - name: Run Fuzz Tests
        run: make fuzztest

  Integration_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Setup Go ENV
        uses: actions/setup-go@v4
        with: 
          go-version: '1.22.5'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt install libzmq3-dev

      - name: Build Containers
        run: make -j2 docker
      
      - name: Download go-mod
        run: go mod tidy

      - name: Run Integration_Test
        run: make integration-test